#!/bin/python

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    level = 0
    S = s
    valleys = 0
    for i in range(len(S)):
        if S[i] == 'U':
            level += 1
        elif S[i] == 'D':
            level -= 1

        if (level == 0 and S[i] == 'U'):
            valleys += 1
    return valleys

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input())

    s = raw_input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
